ersion: 2.0

id: public-mobile-design-system

about:
  title: public-mobile-design-system
  description:
    TELUS Reference Architecture server-side-rendered isomorphic React.js single
    page app, utilizing TELUS Design System styles and Redux state management.

contacts:
  - type: Project Manager
    name: Natasha Lander
    email: natasha.lander@telus.com
    github: NatashaLander
  - type: Developer
    name: Mauricio Mercado
    email: mauricio.mercado@telus.com
    github: maumercado
  - type: Developer
    name: Samantha Vale
    email: samantha.bezerra_vale@telus.com
    github: karlasamantha
  - type: Developer
    name: Ruxandra Fediuc
    email: ruxandra.fediuc@telus.com
    github: ruxandrafed
  - type: Developer
    name: Matt Seburn
    email: matt.seburn@telus.com
    github: mattseburn
  - type: Developer
    name: Bill Li
    email: bill.li@telus.com
    github: billxinli
  - type: Product Owner
    name: Daniel Tyrala
    email: daniel.tyrala@telus.com
  - type: Product Owner
    name: Katarina Sokach
    email: katarina.sokach@telus.com

references:
  - title: Source Code
    uri: https://github.com/telus/public-mobile-design-system

environments:
  - title: Production
    uri: https://public-mobile-design-system-production-starter-kit.c1b9.telusdigital.openshiftapps.com/
    description: Production environment

  - title: Staging
    uri: https://public-mobile-design-system-staging-starter-kit.c1b9.telusdigital.openshiftapps.com/
    description: Staging environment
