# Defines the local environment configuration for our application
#
# Usage:
#   docker-compose build
#   docker-compose up app
#   docker-compose run app test
#   docker-compose run e2e
#   docker-compose run load
#   docker-compose run lighthouse

version: '3'
services:
  app:
    container_name: public-mobile-design-system
    build: app
    environment:
      - APP_ENV=development
    ports:
      - '3000:3000'
