name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Bootstrap project
        run: npm run bootstrap
      - name: Run unit tests
        run: npm run test
      - name: Run linter
        run: npm run lint
