name: 'Build, Lint, Test and Deploy if master'

on: push

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: npm run test
      - run: npm run lint
